repos:
#- repo: https://github.com/golangci/golangci-lint
#  rev: v1.62.2
#  hooks:
#    - id: golangci-lint # Change to golangci-lint-full in future
#      args: [--config=.golangci.yml, --fix]
- repo: local
  hooks:
    - id: go-file-header-checker
      name: Go File Header Checker
      entry: scripts/go_file_header_checker.sh
      language: system
      pass_filenames: false
      always_run: true
