name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4

    - name: Install go-test-coverage
      run: go install github.com/vladopajic/go-test-coverage/v2@latest

    - name: Run build process
      run: |
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        make build
